import type { Metadata } from 'next'
import Link from 'next/link'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href='/'>Главная</Link>
          <Link href='/about'>О нас</Link>
          <Link href='/projects'>Проекты</Link>
        </header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  )
}
